### ISSUE TITLE
select statements doesn't work on PostgreSQL

### ISSUE THREAD

**Issue by aaberg** [aaberg/sql2o#10]
Whe using PostgreSQL, all SELECT statements will fail with message:
org.postgresql.util.PSQLException: ERROR: syntax error at or near "RETURNING"

Seems to be related to [this issue](http://www.postgresql.org/message-id/4BD196B4.3040607@smilehouse.com)

**Comment by degomon** [comment]
How to pass QuirkMode ENUM in spring context (xml) ?

**Comment by pastrehe** [comment]
@degomon 

` <bean id="postgresDS" class="org.apache.commons.dbcp2.BasicDataSource">`<br>`
        <property name="driverClassName" value = "org.postgresql.Driver" />`<br>`
        <property name="url" value ="jdbc:postgresql://host:port/database"/>`<br>`
        <property name="username" value = "user"/>`<br>`
        <property name="password" value = "passwd"/>`<br>`
    </bean>`<br>`
   <bean id="beanPostgresQuirks" class="org.sql2o.quirks.PostgresQuirks" />`<br>`
    <bean id="sql2o" class="org.sql2o.Sql2o">`<br>`
        <constructor-arg>`<br>`
            <ref bean="postgresDS"/>`<br>`
        </constructor-arg>`<br>`
        <constructor-arg>`<br>`
        <ref bean="beanPostgresQuirks" />`<br>`
        </constructor-arg>`<br>`
    </bean> 
`
