### ISSUE TITLE
how to use "inner join" with sql2o to return pojos

### ISSUE THREAD

**Issue by lizhuangs** [aaberg/sql2o#136]
hi,aaberg:
sql2o is a good job!I saw the samples in official website.it's easy and so concise.
but the only question is how can I use "inner join" with sql2o to return the  result "POJO" for me,just like hibernate .the pojo contains other pojos.

Thanks.
tudou

**Comment by aaberg** [comment]
I don't see a good solution to implement this. Closing.

**Comment by niksabaldun** [comment]
IMHO, one-to-many and one-to-one relationships are not a problem, @impeto explained one way to resolve that. Many-to-one, however, is a problem. Say you have a table "cities" which is connected to table "countries" by field "id_country". In Java, "City" class would have a field of type "Country". I can include "id_country" field in query, but sql2o wouldn't know what to do with it, and I couldn't access its value after executeAndFetch(). I can easily retrieve a list of applicable countries in separate query, but I would have no way to connect them with cities. Honestly, I don't know what would be the best approach to handle this problem.
