### ISSUE TITLE
the doc "Integration With Spring Framework" configuration

### ISSUE THREAD

**Issue by ccor** [aaberg/sql2o#141]
<bean id="sql2o" class="org.sql2o.Sql2o">
	<property name="dataSource" ref="mysqlDS"></property>
</bean>
But Sql2o has no defautle constructor, should be that:
<bean id="sql2o" class="org.sql2o.Sql2o">
	<constructor-arg ref="mysqlDS"/>
</bean>

**Comment by kfowlks** [comment]
@ccor There is no need for a default constructor because you can use Spring to pass in a datasource in your configuration. See the below Spring 4.1 XML example as to how to initialize a sql2o object properly in Spring. 

        <bean id="sql2o" class="org.sql2o.Sql2o">				
		<constructor-arg type='javax.sql.DataSource' ref='datasource'/>		
	</bean>

**Comment by aaberg** [comment]
Thanks for clearing this out. I will close this issue. There is still a need to add better documentation for how to use a connection pool without using spring, but that is covered in #143
