### ISSUE TITLE
does sql2o support connection pool?

### ISSUE THREAD

**Issue by medcl** [aaberg/sql2o#143]
if so, will be awesome.

**Comment by kfowlks** [comment]
The above commentators are correct! Hikari works just fine with sql2o and Spring 4.1. Check out the below for an example applicationContext.xml

	<context:component-scan base-package="net.p2pmag.totl" > 
		<context:include-filter type="regex" 
                       expression="net.p2pmag.totl.dao.*DAO*" /> 
		<context:include-filter type="regex" 
                       expression="net.p2pmag.totl.services.*Service*" /> 
	</context:component-scan>
	
	<bean id="datasource" class="com.zaxxer.hikari.HikariDataSource">
	
			<constructor-arg>
		        <bean class="com.zaxxer.hikari.HikariConfig">
		            <constructor-arg>
		                <props>
	                    <prop key="dataSource.url">jdbc:hsqldb:file:c:/home2/app/hsqldb/mydb</prop>
		                    <prop key="dataSource.user">sa</prop>
		                    <prop key="dataSource.password"></prop>
		                </props>
		            </constructor-arg>
		            <property name="dataSourceClassName" value="org.hsqldb.jdbc.JDBCDataSource" />
		        </bean>
		    </constructor-arg>
	</bean>    
	
	<bean id="sql2o" class="org.sql2o.Sql2o">				
		<constructor-arg type='javax.sql.DataSource' ref='datasource'/>		
	</bean>
        
</beans>
