### ISSUE TITLE
DateTimeConverter: Defaults to Timezone.UTC instead of TimeZone.getDefault()

### ISSUE THREAD

**Issue by 4rnstein** [aaberg/sql2o#147]
Using secondary constructur fixes the issue:

new NoQuirks(new HashMap<Class, Converter>() {{
                put(DateTime.class, new DateTimeConverter(DateTimeZone.forTimeZone(TimeZone.getDefault())));
            }})

**Comment by pabl0rg** [comment]
databases like postgres say what timezone a date is in.  In such cases, it would be much better for the converter to use the database's stated timezone.
