### ISSUE TITLE
Ability to log sql query via boolean from Sql2o or Query classes

### ISSUE THREAD

**Issue by sachinwalia2k8** [aaberg/sql2o#157]
This is a simple request but one could avoid writing pesky log statements in multiple places to log sql query.

My take:

1. To define it globally we can make use of Sql2o class.
2. To define per query provide an ability in Query class.

Sql2o and Query both could provide a method something like: 
setSqlLogging(boolean enable, LogLevel ..);

Log Level could decide which level should be used for logging SQL. Default could be debug / error.

**Comment by aaberg** [comment]
I have added logging of the SQL just before the statement is executed. It will log the parsed query, so that parameters are logged as ?. Instead of adding a `setSqlLogging()` or similar, it will simply log queries at DEBUG level, so that it utilizes default logging behavior.
