### ISSUE TITLE
The bind() call also binds elements that has already been manually bound

### ISSUE THREAD

**Issue by yngvesl** [aaberg/sql2o#160]
When I map a pojo with bind(), it seems like the outcome is primarily dictated by the underlying driver sql2o uses. In my case I have a java.util.UUID which is going into an id text field in the database (I do this to achieve some loose coupling to whatever RDBMS in use). However, when I call bind I get the following exception:

java.lang.RuntimeException: Error adding parameter 'id' - Unable to convert between java.util.UUID and JAVA_OBJECT.
    at net.sourceforge.jtds.jdbc.Support.convert(Support.java:632)
    at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.setObjectBase(JtdsPreparedStatement.java:590)
    at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.setObject(JtdsPreparedStatement.java:907)
    at org.sql2o.quirks.NoQuirks.setParameter(NoQuirks.java:52)

I thought I could add "id" manually myself before calling bind() and that bind() then didn't care about that field, but it seems like bind() iterates over all fields anyways. I mean the ideal would be that you have the possibility to explicitly add fields yourself first and that a following call to bind() then respects that and ignore those fields in its "automatic" binding. Then I could add the UUIDs string representation. This change will be 100% backwards compatible.

**Comment by pslacerda** [comment]
This problem also happens to me in sql2o-postgres-1.6.0-RC2 using PostgresQuirks. `bind()` bound all parameters again even if manually added before. I have a `Map<String, Object>` in a field and it is handled as hstore but I really mean jsonb. So I added it using `addParameter(String, String)` and expected `bind()` works as the @yngvesl implied.

**Comment by pslacerda** [comment]
Something like
```java
if (parameters.containsKey(property.name) {
    continue; // already added
}
```

at Query.bind() line 373 will work as intended by @yngvesl 

https://github.com/aaberg/sql2o/blob/master/core/src/main/java/org/sql2o/Query.java#L373
