### ISSUE TITLE
Fetching trigger-generated keys from Oracle

### ISSUE THREAD

**Issue by aaberg** [aaberg/sql2o#161]
Ref discussion on google group:
https://groups.google.com/forum/#!topic/sql2o/k2LwGdSdsb8

**Comment by Adhara3** [comment]
That would be great, yeah.... ;)

**Comment by Adhara3** [comment]
Btw, currently I get an error that has not much sense to me:
```
org.sql2o.Sql2oException: Keys where not fetched from database. Please call executeUpdate(true) to           fetch keys
```
But `executeUpdate(true)` doen not exist in the API.... 

Thanks
Andrea

**Comment by aaberg** [comment]
Year, you are right. That error message is clearly wrong. I'll crate a new issue and get it fixed as fast as possible.

**Comment by aaberg** [comment]
new api:

```java
try(Connection con = sql2o.open) {
    // pass the column name for the column with generated key.
    Long key =  con.createQuery(sql, columnName)
        .addParameter(....)
        .executeUpdate()
        .getKey(Long.class);
}
```

or, if multiple keys are generated:

```java
try(Connection con = sql2o.open) {
    // pass the column name for all columns with generated keys.
    Object[] keys =  con.createQuery(sql, columnName1, columnName2, ..., columnNameN)
        .addParameter(....)
        .executeUpdate()
        .getKeys(Long.class);
}
```

**Comment by harshathota1991** [comment]
Hi, I am getting a ora-01400 cannot insert null into table. 

                long actionId = con.createQuery(sql, "ACTION_ID")
				   .addParameter("axisid", axisId)
                        	   .addParameter("condition", condition)
				   .executeUpdate().getKey(long.class);
It says, cannot insert null into the column action_id. But the column is auto incremented and should return the new value.

First, I have tried with con.createQuery(sql, true). Both ways I am getting the ORCA 1400 error.

Action_id is the auto generated column in Oracle and I need to insert a new row and get back the
auto generated action_id. Could you please suggest on how to solve this.

Please find my sql state ments below:

CREATE TABLE "CDQ"."DQ_AXIS_ACTION"(
    "ACTION_ID" NUMBER NOT NULL,
    "AXIS_ID" NUMBER NOT NULL,
    "CONDITION" VARCHAR2(50) NOT NULL,
    CONSTRAINT "DQ_AXIS_ACTION_PK_INDEX" PRIMARY KEY ("ACTION_ID")
)

CREATE SEQUENCE "DQ_AXIS_ACTION_SEQUENCE" INCREMENT BY 1 START WITH 1 

CREATE OR REPLACE TRIGGER "CDQ"."DQ_AXIS_ACTION_TRIGGER" 
BEFORE INSERT ON "CDQ"."DQ_AXIS_ACTION"
FOR EACH ROW

BEGIN
  SELECT "DQ_AXIS_ACTION_SEQUENCE".NEXTVAL
  INTO   :new.action_id
  FROM   dual;
END;
/

**Comment by harshathota1991** [comment]
Hello Aaberg, 

I am facing the same issue as mentioned in https://groups.google.com/forum/#!topic/sql2o/k2LwGdSdsb8. We are using Oracle and it is returning a oracle.sql.ROWID when I call the getKey after the insert. The insert is successful but the generated key being returned is a oracle.sql.ROWID. 

I see the latest release is 1.5.4. Is the fix for this as mentioned in the google post discussion released or yet to be released. I have tried different methods of createQuery and none works. All returns a rowId object.

Please suggest. Thank you for the help!

Harsha
