### ISSUE TITLE
Fail to add parameter to query when parameter name is only one character

### ISSUE THREAD

**Issue by RasmanTuta** [aaberg/sql2o#166]
The following code will fail with java.lang.StringIndexOutOfBoundsException: String index out of range: 56 at org.sql2o.quirks.parameterparsing.impl.ParameterParser.parse(ParameterParser.java:33)

    count = S2o.getLocalSql2o().createQuery("select count(*) from scheme.table where status =:p", "name").addParameter("p", status).executeScalar(Integer.class);

Found in version 1.5.3

**Comment by aaberg** [comment]
This is now fixed. It was a small error in the parameter parser. The fixed code is released with sql2o 1.5.4
