### ISSUE TITLE
DateTime parsing issue 

### ISSUE THREAD

**Issue by Adhara3** [aaberg/sql2o#169]
We are storing some events in an oracle DB as TIMESTAMP WITH TIME ZONE.
Imagine I have on the Db this value stored: `2015-01-24 12:47:02:198000 EUROPE/BERLIN`
When I perform the query I get two different results if I use Sql2o and the raw javax.sql

    ResultSet executeQuery = connection.createStatement().executeQuery(sql);
    executeQuery.next();
    DateTime dt = new DateTime(executeQuery.getTimestamp(1));

returns `2015-01-24T12:47:02.198+01:00`

while

    Connection open = new Sql2o(dataSorce, new OracleQuirks()).open();
    DateTime dtSql2o = open.createQuery(sql).executeAndFetchFirst(DateTime.class);

returns `2015-01-24T12:47:02.198Z`

I am also in the +01:00 zone, so I really can't see why Sql2o would use UTC.
Is that a bug or am I missing something (very likely, dates make me crazy...)?

Thanks a lot
Andrea

**Comment by Adhara3** [comment]
I see, it's a duplicate of [#147](https://github.com/aaberg/sql2o/issues/147)
I initially though that was resolved for 1.5.3.

Sorry for that.

A

**Comment by aaberg** [comment]
No problem. Until 1.6.0 is released you can used the work arround described in #147.

~lars
