### ISSUE TITLE
Binding in iteration failing

### ISSUE THREAD

**Issue by zsoca8711** [aaberg/sql2o#177]
Hi!

I had a Query and a Pojo.
I did the following

Query x = conn.createQuery(RECORD_TO_PROCESS);
for (MyPojo p : pojoList){
 x.bind(p).executeUpdate();
}

This only did the update on the first pojo, because the binding didn't go away. I found no "clearParameters" method which would unbind.
I suspect the problem is in the Query class, on line 283:

 if (addedParameters.contains( property.name )) continue;

**Comment by FredipusRex** [comment]
Actually, bind() is now unusable except in the simplest one-off query cases. For instance, if you use bind() in the context of a batch query, it will only bind the first object (all others get skipped due to the addedParameters.contains() check). 

Outside of a complete separation of the Query *population* phase from the Query *execution* phase, I think you've only got a few options. 

* Create a method that will clear the addedParameters set and either make it public or call it after each method that completes a unit of work (executeXXX and addToBatch). The inclusion of addToBatch is important, as it completes the unit of work (setting parameters) for a single item within a batch.

* Get rid of the addedParameters concept completely and just document that a bind() acts like any other addParameter call and will overwrite parameters that already exist. If there is a parameter in the POJO that you want to overwrite/skip, simply bind() first and follow with the override.

I'm having to completely rewrite a batch loader due to this bug. I now have to use addParameter for every field in my POJOs. It's kind of negates the "sql2o handles POJOs" aspect of sql2o.

**Comment by FredipusRex** [comment]
For anyone who needs to work around the bind bug, here's an alternate bind method that does the same thing as bind() but does not check for overwriting previous addParameters calls - i.e., it's behaviour is exactly the same as addParameter. As it's not part of the class, it takes Query as its first parameter.

```java
private static Query bind(Query query, final Object pojo) {
    Class clazz = pojo.getClass();
    Map<String, PojoIntrospector.ReadableProperty> propertyMap = PojoIntrospector.readableProperties(clazz);
    for (PojoIntrospector.ReadableProperty property : propertyMap.values()) {
        try {
            if( query.getParamNameToIdxMap().containsKey(property.name)) {
                @SuppressWarnings("unchecked")
                final Class<Object> type = (Class<Object>) property.type;
                query.addParameter(property.name, type, property.get(pojo));
            }
        }
        catch(IllegalArgumentException ex) {
            logger.debug("Ignoring Illegal Arguments", ex);
        }
        catch(IllegalAccessException | InvocationTargetException ex) {
            throw new RuntimeException(ex);
        }
    }
    return query;
}
```

**Comment by aaberg** [comment]
I think you are right, that the bind() method should act as any of the other addParameter() methods. This is also how it worked originally. The behavior was changed when issue #160 was fixed. I realize that this change wasn't thought through.

**Comment by mbraunerDE** [comment]
For all who working with column Mappings

```
private static Query bind(Query query, final Object pojo) {
    Class clazz = pojo.getClass();
    Map<String, PojoIntrospector.ReadableProperty> propertyMap = PojoIntrospector.readableProperties(clazz);
    for (PojoIntrospector.ReadableProperty property : propertyMap.values()) {
        try {
            final String name = query.getColumnMappings()
                .entrySet()
                .stream()
                .filter(e -> {
                    if (query.isCaseSensitive()) {
                        return e.getValue().contentEquals(property.name);
                    } else {
                        return e.getValue().contentEquals(property.name.toLowerCase());
                    }
                })
                .findFirst()
                .map(Map.Entry::getKey)
                .orElse(property.name);
            if (query.getParamNameToIdxMap().containsKey(name)) {
                @SuppressWarnings("unchecked")
                final Class<Object> type = (Class<Object>) property.type;
                query.addParameter(name, type, property.get(pojo));
            }
        } catch (IllegalArgumentException | IllegalAccessException | InvocationTargetException ex) {
            throw new RuntimeException(ex);
        }
    }
    return query;
}
```

**Comment by tomgit2016** [comment]
> For all who working with column Mappings
> 
> ```
> private static Query bind(Query query, final Object pojo) {
>     Class clazz = pojo.getClass();
>     Map<String, PojoIntrospector.ReadableProperty> propertyMap = PojoIntrospector.readableProperties(clazz);
>     for (PojoIntrospector.ReadableProperty property : propertyMap.values()) {
>         try {
>             final String name = query.getColumnMappings()
>                 .entrySet()
>                 .stream()
>                 .filter(e -> {
>                     if (query.isCaseSensitive()) {
>                         return e.getValue().contentEquals(property.name);
>                     } else {
>                         return e.getValue().contentEquals(property.name.toLowerCase());
>                     }
>                 })
>                 .findFirst()
>                 .map(Map.Entry::getKey)
>                 .orElse(property.name);
>             if (query.getParamNameToIdxMap().containsKey(name)) {
>                 @SuppressWarnings("unchecked")
>                 final Class<Object> type = (Class<Object>) property.type;
>                 query.addParameter(name, type, property.get(pojo));
>             }
>         } catch (IllegalArgumentException | IllegalAccessException | InvocationTargetException ex) {
>             throw new RuntimeException(ex);
>         }
>     }
>     return query;
> }
> ```

It works. Thanks!
