### ISSUE TITLE
Support positional parameters

### ISSUE THREAD

**Issue by niksabaldun** [aaberg/sql2o#181]
I was having trouble with INSERT and UPDATE statements, they just wouldn't work, and at one point I realized that sql2o does not support positional SQL parameters. It didn't even enter my mind that basic feature like that would be omitted. Why not support positional parameters? It should be trivial to implement.

**Comment by dimzon** [comment]
Positional parameters is evil. Just use named parameters :)

**Comment by niksabaldun** [comment]
Pronounce something "evil" by fiat and just dismiss it. Wow.

Positional parameters are not evil, of course. They have their legitimate use cases, just like named ones. If you are building SQL dynamically, they are easier to work with and also faster, as there is no name lookup.

If positional parameters are indeed evil, why does Query class support "withParams" method? That is basically the same as using positional parameters, except sql2o first arbitrarily names them "p1", "p2" and so on, and then looks them up in parameter map, in order to determine their index *which is already known*. This is counter-intuitive (and not mentioned in documentation, as far as I can see). It is logical to assume, if you pass an array of unnamed parameters, that those parameters will be interpreted as positional parameters.
