### ISSUE TITLE
Setting setAutoDeriveColumnNames(true) in some kind of "global" level

### ISSUE THREAD

**Issue by alexandremjacques** [aaberg/sql2o#182]
Following the idea of having some kind of global configuration (issue #157), it would be also nice to set  setAutoDeriveColumnNames on a more broad configuration (sql2o instance?).

Since DBs usually follows a naming convention (snake case, camel case, etc.), it is pretty boring (and error prone) to keep setting this on every createQuery.

Regards.

**Comment by neilgrover** [comment]
I created a merge request for this feature. Please see here:
https://github.com/aaberg/sql2o/pull/321
