### ISSUE TITLE
Support for maxBatchRecords

### ISSUE THREAD

**Issue by aartiPl** [aaberg/sql2o#190]
It would be nice to have method on query:
void maxBatchRecords(int max);

When someone will set non zero value on it, then after max additions to Batch, there should be called query.executeBatch().
See e.g.: http://viralpatel.net/blogs/batch-insert-in-java-jdbc/

This is common pattern to avoid OutOfMemory error when adding too many records to batch.
It can be very simply implemented in current solution.

**Comment by zsoca8711** [comment]
I'll get on and develop this and i'll post a pull request on it.
You can review and feeback on my solution :) 

I'll also add test coverage of course.

**Comment by zsoca8711** [comment]
https://github.com/aaberg/sql2o/pull/198
