### ISSUE TITLE
Change Schema before executing Queries.

### ISSUE THREAD

**Issue by ashishranjan30** [aaberg/sql2o#194]
In Native JDBC we can use setCatalog() to change schema. Is there any alternative here in Sql2o to execute queries over different schemas.

**Comment by aaberg** [comment]
You can set the schema directly on the underlying jdbc connection. Example:
    
``` java
try (Connectio con = sql2o.open()) {
    con.getJdbcConnection.setCatalog("theCalalog");

    con.createQury(sql).addParameter("param", var).execute...();
}
```

**Comment by ashishranjan30** [comment]
Thanks. That helped a lot.
