### ISSUE TITLE
Sql2o.beginTransaction() fails to release the connection on failure

### ISSUE THREAD

**Issue by atnak** [aaberg/sql2o#200]
Our connection pool ran out, and log analysis suggests this may be the cause.

When `Sql2o.beginTransaction(int)` [throws an `RuntimeException` at line 254](https://github.com/aaberg/sql2o/blob/master/core/src/main/java/org/sql2o/Sql2o.java#L254), it doesn't seem to be releasing the created-but-soon-to-be-abanded `jdbcConnection`.

I suspect the code should be changed to something like:

```java
Connection connection = new Connection(this, false);

boolean success = false;
try {
    connection.getJdbcConnection().setAutoCommit(false);
    connection.getJdbcConnection().setTransactionIsolation(isolationLevel);
    success = true;
} catch (SQLException e) {
    throw new RuntimeException(e);
} finally {
    if (!success) {
        connection.close();
    }
}

return connection;
```

**Comment by aaberg** [comment]
Thanks for the detailed description. I will fix it right away and include it in the upcoming 1.6.0 release

**Comment by aartiPl** [comment]
Hi, when is there planned a new release? I think that this issue is very important for anyone who wants to use sql2o in production environment. Relaying on v. 1.5.4 is not an option, so only custom builds are possible... I would be very happy to see a new release soon... Thanks in advance!

**Comment by aaberg** [comment]
Hi,

The only thing that remains for before version 1.6.0 release, is to update
some documentation. But since there has been multiple requests to release
it asap, I am considering to release the new version first, and then update
the documentation.

I'll keep you posted!

Regards
Lars Aaberg
