### ISSUE TITLE
Sql2o should not rely on `sun.misc.Unsafe`

### ISSUE THREAD

**Issue by amanteaux** [aaberg/sql2o#208]
`org.sql2o.reflection.UnsafeFieldGetterFactory` and `org.sql2o.reflection.UnsafeFieldSetterFactory` are relying on the `sun.misc.Unsafe` class.

The future of the accessibility of the `sun.misc.Unsafe` class remain uncertain for Java 9.
Moreover, I don't see why it is used in `UnsafeFieldGetterFactory` and `UnsafeFieldSetterFactory`: there is no need to use `sun.misc.Unsafe` to access the value of a field (even a private/final/volatile/static field).

Is there a reason to use `sun.misc.Unsafe` in sql2o that I missed?

**Comment by aaberg** [comment]
It's a performance thing. The performance of setting and getting fields using the unsafe methods is much better compared to using reflection. Sql2o is using a fallback-strategy, so if the `Unsafe` is not available in the jvm, it will fall back to using reflection.

If there is an even better way of doing this in Java 9, we should provider an implementation for that. But, let's wait and see when Java 9 arrives.

**Comment by amanteaux** [comment]
Ok, thank you for the precision!
