### ISSUE TITLE
addParameter doesn't support Joda-Time's LocalDate

### ISSUE THREAD

**Issue by eliandroribeiro** [aaberg/sql2o#214]
`LocalDate birthDate = ...`

`query.addParameter("birthDate", birthDate)` fails (returns nothing).
`query.addParameter("birthDate", birthDate.toString())` works correctly.

Not even `query.addParameter("birthDate", LocalDate.class, birthDate)` works.

Is this an issue?

**Comment by aaberg** [comment]
This should work. 
What database are you using? 
What datatype is the column in the database table?

**Comment by eliandroribeiro** [comment]
MySql 5.5
The column datatype is date.

**Comment by nikku** [comment]
`LocalDate` and `LocalDateTime` seem to not be supported on `TIMESTAMP` columns with sql2o 1.5.x.

**Comment by aaberg** [comment]
When using sql2o with joda-time, it relies on the build-in converters in the joda-time library.
