### ISSUE TITLE
Joda classes should be in a separated dependency

### ISSUE THREAD

**Issue by amanteaux** [aaberg/sql2o#215]
I am using Java 8 so I do not want Joda Time to be in my classpath. Indeed Joda Time classes messes with Java 8 ones: if I want to use `java.time.LocalDate` I have to be careful not to import `org.joda.time.LocalDate`.

However the oracle extension to sql2o is requiring Joda Time through the service provider file `org.sql2o.converters.ConvertersProvider`.
So if I remove Joda Time from my classpath I get the error `ClassNotFoundException: org.joda.time.DateTimeZone` :(

Would it be possible to place the joda converters inside a separate sql2o extension module?

**Comment by amanteaux** [comment]
If it is OK, I can do the change and create a pull request.

**Comment by aaberg** [comment]
Year, that would be a welcome addition! If you are willing to do the change, I will gladly merge it.
