### ISSUE TITLE
Connection.close() is incompatible with Java EE Container Managed Transactions (CMT)

### ISSUE THREAD

**Issue by doganov** [aaberg/sql2o#224]
Automatic rollback on `Connection.close()` is handy, but makes the method unusable in the context of Java EE Container Managed Transaction (CMT). In CMT, `commit()` and `rollback()` are forbidden in application code, since they are supposed to be issued by the container.

It would be great if there is a way to tell the Connection object not to issue `rollback()` on `close()`.

**Comment by aaberg** [comment]
Fixed with pull request #225
