### ISSUE TITLE
getKey failing in PostgreSQL 9.5

### ISSUE THREAD

**Issue by josecollazzi** [aaberg/sql2o#249]
postgreSQL 9.5  (1.5.4 and 1.6.0-RC2)

```
        try (Connection connection = getSql2o().open()) {
            String sqlCreateTable = "CREATE TABLE servicesql.\"country\"(name character varying(255), id SERIAL NOT NULL, description character varying(1024), CONSTRAINT country_id_pk PRIMARY KEY (id));";
            connection.createQuery(sqlCreateTable).executeUpdate();

            String sqlInsert = "INSERT INTO servicesql.\"country\" (\"name\",\"description\") VALUES ('Uruguay','It is a nice country')";
            Object object = connection.createQuery(sqlInsert, true).executeUpdate().getKey();
            System.out.println(object.toString());
        }
```

In version 1.5.4 of sql2o this print "Uruguay", while in 1.6.0-RC2 I get a "syntax error at or near "RETURNING"" 

 in both cases it it should print "1"

It is working when the table is created with id in the first position

```
CREATE TABLE servicesql."country"( id SERIAL NOT NULL, name character varying(255), description character varying(1024), CONSTRAINT country_id_pk PRIMARY KEY (id));
```

I have tested in SqlServer and Mysql and it is working properly (I get "1"), I have executed this queries:

```
-- sqlserver
sqlCreateTable =  CREATE TABLE servicesql."country"(name character varying(255), id INT NOT NULL  IDENTITY (1,1) PRIMARY KEY, description character varying(1024));
sqlInsert = INSERT INTO servicesql."country" ("name","description") VALUES ('Uruguay','It is a nice country')

-- MySql 

sqlCreateTable = CREATE TABLE `service-sql`.`country`(name character varying(255), id INT NOT NULL AUTO_INCREMENT, description character varying(1024), CONSTRAINT country_id_pk PRIMARY KEY (id));
sqlInsert = INSERT INTO `service-sql`.`country` (`name`,`description`) VALUES ('Uruguay','It is a nice country')
```

Edited: I have try with two drivers and get the same result:

```
        <dependency>
            <groupId>com.impossibl.pgjdbc-ng</groupId>
            <artifactId>pgjdbc-ng</artifactId>
            <version>0.6</version>
        </dependency>
```

and 

```
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4-1200-jdbc41</version>
        </dependency>
```

**Comment by DanStout** [comment]
Are you using PostgresQuirks? I think that may solve your issue.

Add this maven dependency:

```
<dependency>
	<groupId>org.sql2o.extensions</groupId>
	<artifactId>sql2o-postgres</artifactId>
	<version>1.6.0-RC2</version>
</dependency>
```

and instantiate your Sql2o instance like so: `new Sql2o(src, new PostgresQuirks());`

**Comment by josecollazzi** [comment]
Thank you for your fast response @DanStout, With this changes I still have the same result.

**Comment by DanStout** [comment]
Hmm.. What is the result if you change your insert SQL to this?
```
String sqlInsert = "INSERT INTO servicesql.\"country\" (\"name\",\"description\") VALUES ('Uruguay','It is a nice country') RETURNING id";
```

**Comment by josecollazzi** [comment]
I have try with that query but I get errors:

String sqlInsert = "INSERT INTO servicesql.\"country\" (\"name\",\"description\") VALUES ('Uruguay','It is a nice country') RETURNING id";  

If I execute with returnGeneratedKeys = true
````
Object object = connection.createQuery(sqlInsert, true).executeUpdate().getKey(); //Error in executeUpdate, ERROR: syntax error at or near "RETURNING" (the query is like INSERT INTO servicesql."country" ("name","description") VALUES ('Uruguay','It is a nice country') RETURNING id RETURNING *)
````
If I execute with returnGeneratedKeys = false
````
Object object = connection.createQuery(sqlInsert).executeUpdate().getKey(); //Error in executeUpdate, A result was returned when none was expected.
````

**Comment by DanStout** [comment]
Well, this isn't a perfect solution, but it seems like it would work if you did:

```
Object object = connection.createQuery(sqlInsert).executeScalar();
```

I'm curious as to whether the problem here is with PostgreSQL's JDBC drivers, or Sql2o. I feel like it's probably the former, but you could verify that by trying to write this without Sql2o. Something like:

```
PreparedStatement stmt = connection.getJdbcConnection()
	.prepareStatement(insertSql, PreparedStatement.RETURN_GENERATED_KEYS);
stmt.setString(1, "Uruguay");
stmt.setString(2, "nice");
stmt.executeUpdate();

ResultSet rs = stmt.getGeneratedKeys();

while (rs.next())
{
	Object obj = rs.getObject(1);
}
```

**Comment by josecollazzi** [comment]
I get these values:

````
 while (rs.next())
{
     Object obj1 = rs.getObject(1); //"Uruguay"
     Object obj2 = rs.getObject(2); //"1"
     Object obj3 = rs.getObject(3); //"It is a nice country"
}
````

It is different of what I expect, but it is a work around for my problem.

Thank you @DanStout

**Comment by josecollazzi** [comment]
It was a bug in the version of postgres driver fix the problem:

Upgraded from:
````
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4-1200-jdbc41</version>
        </dependency>
```
to:
````
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.4.1211</version>
        </dependency>
````

Thanks again for you help @DanStout

**Comment by josecollazzi** [comment]
I reopen this issue because even if works using getJdbcConnection, it doesn't work with the library directly.
PostgreSQL return all the fields when is using getGeneratedKeys http://stackoverflow.com/a/19767751

org.sql2o.Connection#setKeys line 182 is adding only the first key

**Comment by ahardworker** [comment]
Whenever we need a returning value, we use executeScalar(ReturnValueType.class). Hope this helps

**Comment by josecollazzi** [comment]
Hi @ahardworker  the problem was org.sql2o.Connection#setKeys line 182 is adding only the first key, I have fix the problem in in other way. There isn't an

**Comment by josecollazzi** [comment]
Thanks @ahardworker  The problem is that org.sql2o.Connection#setKeys line 182 is adding only the first key. I returning a list of all keys, not a perfect solution neither. I have fix the problem  in my program in other way, out of the scope of this library.
(sorry I closed by mistake)

**Comment by aaberg** [comment]
https://github.com/aaberg/sql2o/pull/255
