### ISSUE TITLE
Writing error in docs

### ISSUE THREAD

**Issue by neo7BF** [aaberg/sql2o#257]
Sorry, I do not know if this is the right place.

Here: http://www.sql2o.org/
at section "Plain JDBC" in the cycle on ResultSet the task created it is never added to the list created at the top of section.

**Comment by DanStout** [comment]
I think you want the [Sql2o website repository](https://github.com/aaberg/sql2o-website).

**Comment by neo7BF** [comment]
Ok, Thanks!

**Comment by aaberg** [comment]
No, actually, this is the right place. The [sql2o website repository](https://github.com/aaberg/sql2o-website) is a new website in progress. The current sql2o website is a little outdated :)

**Comment by aaberg** [comment]
Fixed now. Thx @neo7BF !
