### ISSUE TITLE
Website is broken (no style for /docs/configuration/)

### ISSUE THREAD

**Issue by reallinkD** [aaberg/sql2o#258]
The page /docs/configuration/ ("Configuration") is completely without any style, probably due to the usage of absolute URLs in the HTML.

**Comment by aaberg** [comment]
Wow! This was strange!
The base url is referenced through a variable in the page. The variable is declared as ../../ on a template page for all docs pages. This has worked for years! But, apparently, it doesn't anymore... 
I had to add the base page variable to all individual docs-pages, then it works again.

The sql2o website is build on [jekyll](https://jekyllrb.com/) hosted by [github pages](https://pages.github.com).

Thanks for reporting this!
