### ISSUE TITLE
Fetch Data Lazily not getting complete data

### ISSUE THREAD

**Issue by toshim45** [aaberg/sql2o#259]
Pls help,
I use http://www.sql2o.org/docs/fetching-data-lazy for stream data from database to csv.
Let say I have 400k rows in table X, then I use executeAndFetchLazy, I got the result and unfortunately it less than 400k.
Then I set up for mini table just 5 rows, then I use executeAndFetchLazy, the result is also less than 5.
Then I use executeAndFetch ( http://www.sql2o.org/docs/fetching-data ) and for 5 rows it returns 5, hmm what's wrong with executeAndFetchLazy ? 
Even I use example in http://www.sql2o.org/docs/fetching-data-lazy also not getting complete data.
The missed data is not always the last row, if we fetch 5 rows, it possible row 2 and or 3 are missing.

**Comment by aaberg** [comment]
Hi @toshim45,

I will try to reproduce the problem. Could you please provide the following information:

- What sql2o version do you use?
- What database and jdbc driver do you use? 

Regards
Lars Aaberg

**Comment by toshim45** [comment]
Hi @aaberg ,
Thanks for your fast response, cool.
I use sql2o 1.6.0-RC3 & postgresql 9.4-1206-jdbc4 and also I tried hsqldb 2.3.4.

Regards

**Comment by aaberg** [comment]
Do you have a code-snippet that reproduces the problem with hsqldb?

**Comment by toshim45** [comment]
Wait @aaberg if I tried with just simple query it works, I attach the file.
In my case above I did join 2 tables. I'll try to debug, I'll let u know if my code fixed or any exception raised.
[streamToCSVTest.txt](https://github.com/aaberg/sql2o/files/660736/streamToCSVTest.txt)

sorry for troubling u

**Comment by aaberg** [comment]
Ok, cool. Let me know what you find out.

**Comment by toshim45** [comment]
@aaberg sorry, my mistake, the culprit is I call iterator inside for each loop
```java
try(ResultSetIterable<MigrationMock> resultSetMigrationMocks =
conn.createQuery(SELECT).executeAndFetchLazy(MigrationMock.class)) {
                        for (MigrationMock migrationMock : resultSetMigrationMocks) {
                            if (resultSetMigrationMocks.iterator().hasNext()) // this is the cluprit
                            csvWriter.writeNext(new String[]{
                                    String.valueOf(migrationMock.getId()),
                                    String.valueOf(migrationMock.getBalance()),
                                    formatter.format(migrationMock.getCreated())});
                        }
                    }
```

Thank you.

**Comment by aaberg** [comment]
No problem! I'm just happy you solved your problem :)

Regards
Lars Aaberg
