### ISSUE TITLE
The parameter inside quotes is not parsed

### ISSUE THREAD

**Issue by ppoffice** [aaberg/sql2o#261]
When I used the following SQL Server statement:
```sql
SELECT *
FROM points
where device = :device and DATEDIFF(DAY, created_at, ':date') = 0
```
and tried to `addParameter("date", date)`, I got a NullPointerException implies that the statement does not have a parameter named `date`.
So I went through the sql2o code and found that in the `DefaultSqlParameterParsingStrategy`, quotes(`QuoteParser`) are parsed before parameters(`ParameterParser`), and the parsed statement is:
```sql
SELECT *
FROM points
where device = ? and DATEDIFF(DAY, created_at, ':date') = 0
```
This results in a situation where the actual date parameter is not found. Is this a bug or just my misuse?

**Comment by aaberg** [comment]
Hi, sorry for the late reply!

It is not possible to use parameters within quotes. Everything within quotes is interpreted as strings.

If you want to convert a parameter to a varchar in your query, you could use the [CAST](https://msdn.microsoft.com/en-us/library/ms187928.aspx) transact sql method

But the DATEDIFF method doesn't take a string argument, so you should probably just ditch the quotes, and write:
``` sql
SELECT *
FROM points
where device = ? and DATEDIFF(DAY, created_at, :date) = 0
```
And make sure the date parameter is added as a java.util.Date.

**Comment by ppoffice** [comment]
You are right. Thank you!
