### ISSUE TITLE
It's there a way to escape colon (:)?

### ISSUE THREAD

**Issue by kafm** [aaberg/sql2o#268]
I've a query where I need to provide the date format as 'yyyy-MM-dd HH24:MI:SS'.
Sql2o interprets the MI and SS as parameters.
It's there a way to prevent this behaviour ?
I've tried also to escape it with \\: with no success .

**Comment by mbraunerDE** [comment]
Have you tried to pass your date format as paramter like

```
createQuery("select date_format(date,:format) from table")
.addParamter("format","yyyy-MM-dd HH24:MI:SS");
```

I think it should work

**Comment by aaberg** [comment]
You should always supply parameters as parameters, like @mbraunerDE suggests.
This will also let you supply a date (as a date), instead of as a string, so you don't have to format the date.

**Comment by kafm** [comment]
Thanks for the replay. It's an old issue... At the time, what I wanted was to be scape de ':' character... I gave the date as example but it can be anything... 
In my opinion, I shouldn't have to alter the java code everytime my code requires a parameter with the character ':'
