### ISSUE TITLE
Please add support for Java8 java.time.LocalDate

### ISSUE THREAD

**Issue by mvysny** [aaberg/sql2o#282]
Thank you for your wonderful library, I'm integrating it into my framework (Vaadin on Kotlin) and it works flawlessly. One thing though: if I have a pojo with `java.time.LocalDate`, it seems that it cannot be mapped since reading such pojo from a database will result in

```
at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at org.sql2o.reflection.MethodAccessorsGenerator$2.setProperty(MethodAccessorsGenerator.java:126)
	at org.sql2o.DefaultResultSetHandlerFactory$4.handle(DefaultResultSetHandlerFactory.java:180)
	at org.sql2o.PojoResultSetIterator.readNext(PojoResultSetIterator.java:34)
	at org.sql2o.ResultSetIteratorBase.safeReadNext(ResultSetIteratorBase.java:87)
	at org.sql2o.ResultSetIteratorBase.hasNext(ResultSetIteratorBase.java:52)
	at org.sql2o.Query.executeAndFetch(Query.java:455)
	at org.sql2o.Query.executeAndFetch(Query.java:441)
```
It seems that the `type` is correctly of type LocalDate, however actual value is `java.sql.Date`. I'm using H2, the database column type is `DATE`. Thanks!

**Comment by mvysny** [comment]
JDBC 4.2 are now required to support `java.time.LocalDate` in `ResultSet.getObject(int columnIndex,
Class<T> type)` so perhaps we can use that to our advantage.

**Comment by zapodot** [comment]
@mvysny You are right about JDBC 4.2! If you are lucky enough to have a updated JDBC driver it works perfectly now as well. At least I had no problem mapping from a H2 DATE field to a LocalDate field using an updated H2 driver.
If your chosen DBMS does not currently have an updated driver or you can't use it for some reason you may implement the org.sql2o.convertes.Converter<T> interface your self

**Comment by zapodot** [comment]
@mvysny: I have added a page on the Wiki on how to implement and enable a custom datatype Mapper https://github.com/aaberg/sql2o/wiki/Implementing-and-using-custom-converters
Good luck!

**Comment by mvysny** [comment]
Thanks, that looks good! One question though: How can I add converters to already existing Quirks object, returned by the `QuirksDetector.forURL(hikariConfig.jdbcUrl)` call?

**Comment by mvysny** [comment]
That worked like a charm, thank you!

**Comment by srbattula** [comment]
I am using Spring Boot Starter JDBC with Sql20. Can you suggest a way to handle this?
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>

**Comment by srbattula** [comment]
This helped me to resolve this problem
https://github.com/aaberg/sql2o/wiki/Implementing-and-using-custom-converters
But it would be nice without having this work arounds by part of the library.

**Comment by diyfr** [comment]
* Java version 8  
* Sql2o version 1.6.0  
* Sql2o-postgres version 1.6.0  
* Postgres JDBC  version 42.2.5 (JDBC 4.2)  

Postgres table property 'DATE'  
Object with LocalDate property  

On Class MethodAcessorsGenerator, Method Setter newSetter  
I see   
method setDate(java.time.LocalDate)
type= java.time.LocalDate
value = java.sql.Date
-> IllegalArgumentException ClassCastException

No LocalDate Converter found in org.sql2o.converters.Convert.java

Or @srbattula in documentation you write :

` Hint: if you have an updated JDBC driver you don't need to do this by hand as mapping to java.time.LocalDate should work out of the box.`

[PostgreSql documentation ](https://jdbc.postgresql.org/documentation/head/8-date-time.html)

**Comment by srbattula** [comment]
You could use the following snipped to use LocalDate:

public class LocalDateConverter implements Converter<LocalDate> {
    @Override
    public LocalDate convert(final Object val) throws ConverterException {
        if (val instanceof java.sql.Date) {
            return ((java.sql.Date) val).toLocalDate();
        } else {
            return null;
        }
    }

    @Override
    public Object toDatabaseParam(final LocalDate val) {
        if (val == null) {
            return null;
        } else {
            return new
java.sql.Date(val.atStartOfDay().toInstant(ZoneOffset.UTC).toEpochMilli());
        }
    }
}


Thanks & Regards


M: +91 7032643557
W: http://www.srithripurasoft.com
