### ISSUE TITLE
How to use like match?

### ISSUE THREAD

**Issue by ysdxz207** [aaberg/sql2o#283]
My sql is :
    select * from permission where 1 = 1 and permission_name like '%:permissionName%' ;
I am using 'query.addParameter("permissionName", "select")'.
Error is :
    Failed to add parameter with name 'permissionName'. No parameter with that name is declared in the sql.

**Comment by ysdxz207** [comment]
I saw the source found that if I use quote :permissionName will not be replaced with "?".
So how should I write my sql?

**Comment by zapodot** [comment]
This should work:
SQL: `select * from permission where 1 = 1 and permission_name like :permissionName;`
Java: `query.addParameter("permissionName", "%select%")`

Please report back if you still can't get it to work

**Comment by ysdxz207** [comment]
It works!
Thank you very much!
