### ISSUE TITLE
Memory leak in org.sql2o.Connection while keeping it always open

### ISSUE THREAD

**Issue by yar1k0v** [aaberg/sql2o#289]
First of all, I want to say that I really appreciate the job of the maintainers of this library.

I've found out that org.sql2o.Connection keeps all statements in a HashSet if a connection keeps open and that will obviously lead to a mem leak.

Here is an example of how I make a query to a database
`return mConnection.createQuery("select id, name, model, company from cars").executeAndFetch(Car.class);`
mConnection is an instance of org.sql2o.Connection.

While creating an instance of a Query class, it adds an SQL statement to a connection's statement HashSet. Query class implements AutoCloseable and inside its close method, it removes the cached prepared statement from the connection's HashSet.
So, in case when I want to keep the connection always open, as I see, I need to make queries in this way
`try (Query query = mConnection.createQuery(statement)) {
            return query.executeAndFetch(Car.class);
        }`

Please tell me if there is another way of making a request with an open connection or I shouldn't keep it open or something else, cause I haven't seen anything about connection or query management in the documentation.

I think that it is really not obvious that a developer should call close() on an instance of a Query after calling executeAndFetch() method and I suggest it would be better to call close() inside executeAndFetch(), but that is just my opinion.

**Comment by zapodot** [comment]
Hi @yar1k0v! The Connection object should be considered to be an external resource (like: java.sql.Connection) that indeed should be closed as soon as posible (or handed back to a ConnectionPool). And that is also why both the _org.sql2o.Connection_ class and the _org.sql.Query_ class is AutoClosable. Looking at the source for the Connection class will show that the Statements are closed if it has not already [been closed.](https://github.com/aaberg/sql2o/blob/77813272b0195188cab6c4bd82f92bd7143379d6/core/src/main/java/org/sql2o/Connection.java#L276). 

A good pattern should be to use the Try-With-Resources pattern (supported on Java version 7 and higher):

```
final Sql2o sql2o = //...
try(final Connection connection = sql2o.open(); 
    final Query query = connection.createQuery("SQL")) {
  // do stuff with the query
}
```

Having said that the documentation on Connection and Query handling is obviously not good enough and should be improved.

**Comment by dimzon** [comment]
Just use simple universal rule - always close AutoClosable regardless used
library - this keeps your code clean and safe. AutoClosable contract means
you must free object regardless inner implementation (implementation can be
changed)

20 дек. 2017 г. 9:04 PM пользователь "Yaroslav Kovalov" <
notifications@github.com> написал:

**Comment by dimzon** [comment]
Just remember always check for each object (not only for sql2o but for any
libraries)   does it implement AutoClosable and use try-with-resource. This
simple rule will save your life sometime ;) Same rule for dotNet
(IDisposable interface). Easy to remember, easy to follow...

21 дек. 2017 г. 3:46 PM пользователь "Yaroslav Kovalov" <
notifications@github.com> написал:

**Comment by yar1k0v** [comment]
@dimzon TY for an advice, as I said I'm familiar with this pattern, but this issue is about an inefficient  cache of statements inside the Connection object. If you keep the connection open, it will cache all the queries you make including parameters.
