### ISSUE TITLE
Is not no longer updated, 1.6.0-RC3 has now been a long time

### ISSUE THREAD

**Issue by objectboy2016** [aaberg/sql2o#290]
Is not no longer updated, 1.6.0-RC3 has now been a long time

**Comment by devMls** [comment]
then maybe is a risk adopt this library in new projects?

**Comment by thedarkdestructor** [comment]
So, is anyone still working on the project? Developers are looking for help to make it progress somehow?

We are currently using it in several project and maybe we can provide some kind of help for the future...

**Comment by mbraunerDE** [comment]
+1 

We use it still in our projects and want to use it in future. Should anybody fork it and port it to java 8?

**Comment by zapodot** [comment]
I can not speak for @aaberg but I do think the ambition in the short term is to release v. 1.6.0 based on the latest commits in the master branch. @mbraunerDE I do think we should start a 2.0 branch that moves the minimum Java target to Java 8. In addition, to get more contributors would be nice. I will have a chat with the project owner ASAP and see how it can be managed better by the community in the future.

**Comment by kkrgwbj** [comment]
This project is not expected to be updated. It is recommended that everyone go to JOOQ or jdbi

**Comment by zapodot** [comment]
@kkrgwbj I do think you are mistaken but as for any other opensource project it needs an active community to thrive. So we definitely need to build that in some way

**Comment by hamza-soussou** [comment]
Could we expect a stable 1.6.0 version or the project is dead forever?

**Comment by Ghost93** [comment]
any updates on this?

**Comment by prodsey** [comment]
Any updates or progress? Will there be new a release?

**Comment by sisbr** [comment]
it's still active this project?

**Comment by maqarg** [comment]
any news????

**Comment by maqarg** [comment]
Why this project Is stopped?

**Comment by zapodot** [comment]
@prodsey you are right,  Sql2o will not be compatible with versions of Java after v. 1.8. To make it compatible with Java 9+ will require a major rewrite. The community is more than welcome to step up and make contributions if you want to see this happen in the future 👍

**Comment by zapodot** [comment]
Closing this issue as 1.6.0 was finally released this weekend 👍
