### ISSUE TITLE
Is there a simpler way to insert into table that has many columns?

### ISSUE THREAD

**Issue by Lumos-Nox** [aaberg/sql2o#295]
I have a table with many columns, and the sql is like:
```
String sql = "insert into tb values(:col0, :col2, col3, ..., :col255)";
```
Therefore I need to write addParameter statements like:
```
con.createQuery(sql)
        .addParameter("col0", value0)
        .addParameter("col1", value1)
        ...
        .addParameter("col255", value255)
        .executeUpdate();
```
For simplicity, I want to rewrite the code like:
```
String sql = "insert into tb values(:colList)";
con.createQuery(sql)
        .addParameter("colList", arrayList)
        .executeUpdate();
```
where arrayList is an ArrayList type that stores value0, value2, ..., value255.

Note that I've tried to use bind(), it still requires me to write too many lines of code. The issue "addParameter with a list #146" is similar to my question. Thanks in advance.

**Comment by zapodot** [comment]
You may use the "withParameters" that allows providing parameters as a variable length array. Parameters are then specified in the SQL string using position indexes (p1, p2 and so on).

For instance:
```java
final String sql = "insert into tb values(:p1, :p2, :p3)";
con.createQuery(sql)
        .withParameters("colList", paramValue1, paramValue2, paramValue3)
        .executeUpdate();
// alternative: convert list to array as: // .withParameters("colList", arrayList.toArray(new Object[]{})
```

**Comment by Lumos-Nox** [comment]
Appreciate it very much. But I think '.withParameters' should be replaced with '.withParams' in practice. @zapodot

**Comment by devMls** [comment]
if i remember bind method help:

con.createQuery(sql)
      .bind(object)
        .executeUpdate();

where object fields have the same names that parameters.
