### ISSUE TITLE
Convert.registerConverter Deprecated

### ISSUE THREAD

**Issue by fredericoregateiro** [aaberg/sql2o#304]
The Convert.registerConverter method is Deprecated, what can i use to register custom converters?

Thanks,
Frederico

**Comment by fredericoregateiro** [comment]
I cannot find anything on the documentation to point me on the right direction.
Anyone knows how to use custom converters correctly?

**Comment by zapodot** [comment]
The Sql2o has several constructors that allows you to specify your own Quirks instance that in turn may be used to register custom converters
```java
Quirks quirks = new NoQuirks(){
    {
        converters.put(TypeToConvert.class, new CustomConverter());
    }
};
DataSource dataSource = // 
Sql2o sql2o = new Sql2o(dataSource, quirks);
```

**Comment by mbraunerDE** [comment]
Does this https://github.com/aaberg/sql2o/wiki/Implementing-and-using-custom-converters help you?

**Comment by zapodot** [comment]
Closing this issue as @fredericoregateiro should now have enough information available to resolve this
