### ISSUE TITLE
Warnings with Java 11, possible future denied operation

### ISSUE THREAD

**Issue by Marco-Sulla** [aaberg/sql2o#331]
Using sql2o with Java 11, I get this warning:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.sql2o.reflection.MethodGetter (file:/home/marco/.gradle/caches/modules-2/files-2.1/org.sql2o/sql2o/1.6.0-RC3/9a774fb6de6e93f0c16e6ad927ad379500a56776/sql2o-1.6.0-RC3.jar) to method java.lang.String.getBytes(byte[],int,byte)
> WARNING: Please consider reporting this to the maintainers of org.sql2o.reflection.MethodGetter
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by zapodot** [comment]
Sql2o is not Java 11-compatible. The latest supported release is Java 8. To support Java 11 it will need a major rewrite which for the moment is not planned in the near future

**Comment by Marco-Sulla** [comment]
Well, I use sql2o it with Java Azul Zulu 11 without problems. I only signaled the warning to inform you about possible future incopatibilities.
