### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by artelk** [aaberg/sql2o#351]
Why not create a new release 1.6.1 with recent fixes so it will be seen the project is alive? 😃

**Comment by jehrenzweig-leagueapps** [comment]
As far as I can tell, this project is dead in the water right now.  The repository's owner (@aaberg) has been focused on other activities for the past few years -- consulting, from the looks of it.  Unit tests have been broken for the last ~3yrs.  There are currently 28 open pull requests.  It's unlikely that any of this will change, unless there's enough interest in this project to fork it & work on the outstanding issues there.

**Comment by aaberg** [comment]
Version 1.7.0 has been released. Please read the announcement here
https://github.com/aaberg/sql2o/discussions/365
