### ISSUE TITLE
SQL2o 1.6.0 Compatabile with JDK 17/ OpenJDK 17 ?

### ISSUE THREAD

**Issue by AmansinghtomarLN** [aaberg/sql2o#362]
Hi Team / Developers, 
 
I just wanted to make sure wheather SQL2o is compatable with JDK 17 / Open JDK 17 or not ?

Also Do we have any method or class where we can find out the expected pojo properties name for the resultSet that we are executed for the query ?

Please help me in finding the answers.

**Comment by weeklynote** [comment]
已收到，我会尽快回复你！
                     ——刘劲字

**Comment by aaberg** [comment]
Sorry for the late reply. From Sql2o 1.7.0, which was released recently, the library is automatically tested with newer LTS versions of Java (11, 17 and 21).
Please read the announcement here https://github.com/aaberg/sql2o/discussions/365
