### ISSUE TITLE
Javadoc has an issue with the CDN

### ISSUE THREAD

**Issue by ullenboom** [aaberg/sql2o#371]
![image](https://github.com/aaberg/sql2o/assets/5071169/b58e9740-0226-48c1-9e6c-888d2e7aeca2)

![image](https://github.com/aaberg/sql2o/assets/5071169/b8d78813-06bb-49b7-ba24-9daa20f6cdae)

**Comment by aaberg** [comment]
Hi @ullenboom,
Thanks for bringing this to my attention. I've updated the javadoc server with the newest versions and fixed the error you experience. Can you please verify that it works for you now?
