### ISSUE TITLE
changes breaking compatibility

### ISSUE THREAD

**Issue by dimzon** [aaberg/sql2o#78]
```
    private boolean caseSensitive;
    private boolean autoDeriveColumnNames;
    private Map<String, String> columnMappings;
```
this properties looks like common but are related to **concrete** ResultSetHandlerFactory implementation... I propose to make able to change whole ResultSetHandClerFactory implementation. The default one will have those properties so you can cast to DefaultResultFactory class and set them...

Or according   GoF patterns this settings can be more generic as ```PropertyBindingStrategy``` api....
 
Any of those changes will break backward compatibility. So I propose to finalize current version and reinvent refactoring wheel...

**Comment by aaberg** [comment]
Closing. No longer relevant.
