### ISSUE TITLE
Transaction management

### ISSUE THREAD

**Issue by dimzon** [aaberg/sql2o#89]
I'm a big fun of try-with-resource and propose this pattern for transaction management for new release

``` java
try(Transaction tr= cn.beginTran(TransactionIsolation.REPEATABLEREAD){
    // some actions
    tr.commit();
} // rollback if not commited in close()
```

**Comment by Adhara3** [comment]
"Transaction in transaction" would be great for testing 
Scenario:
1. you want the test to open a transaction
2. the tested object opens an internal transaction and commits/rolls back, 
3. in the test you assert and finally roll back.

A
