### ISSUE TITLE
automatic Quirks detection

### ISSUE THREAD

**Issue by dimzon** [aaberg/sql2o#96]
it's possible to try to detect Database-related Quirks during sql2o instance creation.
for old DriverManager approach it's possible to look @ uri:
```java
        if(url.startsWith("jdbc:db2:")) return db2;
        if(url.startsWith("jdbc:db2j:net:")) return db2;
        if(url.startsWith("jdbc:ids:")) return db2;

        if(url.startsWith("jdbc:oracle:")) return oracle;
```

for ```DataSource``` and other JDBC objects it's possible to look @ className:
```java
        final String name = dataSource.getClass().getName();
        if(name.startsWith("com.ibm.db2.jcc.")) return db2;
        if(name.startsWith("oracle.jdbc.")) return oracle;

```

it's possible to put database-related Quirks into different jars so to detect proper Quirk I propose to use ```java.util.ServiceLoader<QuirksFactory>```
```java
public interface QuirksFactory {
    // can return null value
    Quirks forUrl(String url);
    // can return null value
    Quirks forObject(Object jdbcObject);
}
```  

```java
 private static final ServiceLoader<QuirksFactory> qurksSetLoader
     = ServiceLoader.load(QuirksFactory.class);

//....

 public static Quirks getQuirks(String uri) {
     for (QuirksFactory cp : quirksSetLoader) {
         Quirks enc = cp.forUrl(encodingName);
         if (enc != null)
             return enc;
     }
     return null;
 }

```
PS. according my own experience "Quirks" is in tight relation with concrete JDBC driver so having to support 2 different JDBC drivers for same DB mostly like you need 2 different "Quirks"
Example: MSSQL SERVER (Microsoft own driver vs jDTS)

**Comment by aaberg** [comment]
Closing. This is fixed in master branch.
